### ISSUE TITLE
TA3 / TA2 interface compliance

### ISSUE THREAD

**Issue by cdbethune** [NewKnowledge/goat-d3m-wrapper#1]
For both forward and reverse primitives:

1.  Primitives can just be `transformer.TransformerPrimitiveBase` since only the `produce` method is doing any work.
2.  Arguments are currently passed to the `produce` call as parameters.  These need to be defined as hyperparameters instead.
3.  Input may be easier to work with as a `container.DataFrame`, with a hyperparameter indicating the column to use as the string source.  You can leave it as a list, but that means the calling pipeline has to include operations to extract the column of interest from a `container.Dataframe`, then convert that column into a `container.List` for input.  Unicorn and Croc currently accept a dataframe as input and a source column as a hyperparameter.
4.  Output needs to be a `CallResult` that wraps the return value to be compliant with the API.
5.  That return value would be easier to work with if it is a `container.DataFrame`.  When TA2 finishes executing a pipeline for TA3, it will call `to_csv` on the pipeline output, and pass TA3 a URI to the serialized output.  Returning a list means that the pipeline needs to have a an operation at the end that converts the list to a `container.DataFrame` so that it can be uniformly serialized.

**Comment by azunre** [comment]
Thanks, will get on this asap

**Comment by azunre** [comment]
I have updated both forward and reverse based on the above and have successfully tested it on the latest version of the docker image. Currently submitting to d3m. Didn't address point 1. above (transformer.* etc) -> as I need to investigate more what this means. Please test when you can and let me know how it goes for you.

**Comment by azunre** [comment]
Resolved!
